---
# This playbook deploys a simple standalone Tomcat 7 server. 

- hosts: pdzEtl 
  remote_user: ubuntu
  sudo: yes
  vars_files: 
    - group_vars/tomcat-servers

  roles:
    - tomcat
    - deployPdzEtl 
